services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: superman
      MYSQL_DATABASE: farmpump
      MYSQL_USER: farmuser
      MYSQL_PASSWORD: superman
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    command: python app.py
    depends_on:
      - mariadb
    networks:
      - app-network
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://user:userpassword@mariadb/myapp

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - app-network

  pump_controller:
    build:
      context: .
      dockerfile: Dockerfile.pump_controller
    volumes:
      - ./pump_controller:/app
    working_dir: /app
    command: python pump_controller.py
    depends_on:
      - mariadb
    networks:
      - app-network
    environment:
      - DATABASE_URL=mysql+pymysql://user:userpassword@mariadb/myapp

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
